### ISSUE TITLE
Facts distribution does not work with inline vaulted variables

### ISSUE THREAD

**Issue by tmgstevens** [cloudera-labs/cloudera-deploy#16]
https://github.com/cloudera-labs/cloudera-deploy/blob/a14eefdef84774024dcbf4dcd7187cb4979fb854/roles/cloudera_deploy/tasks/distribute_facts_to_inventory.yml#L43

Error message:
`The full traceback is:
Traceback (most recent call last):
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 585, in _execute
    self._task.post_validate(templar=templar)
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/playbook/task.py", line 307, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/playbook/base.py", line 431, in post_validate
    value = templar.template(getattr(self, name))
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/template/__init__.py", line 840, in template
    disable_lookups=disable_lookups,
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/template/__init__.py", line 795, in template
    disable_lookups=disable_lookups,
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/template/__init__.py", line 1057, in do_template
    res = j2_concat(rf)
  File "<template>", line 14, in root
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/template/__init__.py", line 255, in wrapper
    ret = func(*args, **kwargs)
  File "/home/centos/.local/lib/python3.6/site-packages/ansible/plugins/filter/core.py", line 209, in from_yaml
    return yaml.safe_load(data)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/centos/.local/lib/python3.6/site-packages/yaml/constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!vault'
  in "<unicode string>", line 395, column 26:
    krb5_kdc_admin_password: !vault |`

**Comment by Chaffelson** [comment]
Working as intended I think - all these variables should be in cluster.yml to avoid the pre-parsing that definition.yml goes through to check deployment validity and avoid being logged unencrypted.
